set nu
syntax on
colorscheme slate
set tabstop=4                " Nombre de colonnes pour la tabulation
set shiftwidth=4             " Nombre de colonnes pour l'indentation
" set expandtab              " Convertir les tabulations en espaces
set mouse=a                  " Prendre en compte la souris pour se déplacer
set clipboard=unnamedplus    " Partage du presse-papier
